// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkRxRlOELSiu81nw0KF-ZZfQGynLzlHhM',
    appId: '1:1010007606218:web:0769e3944a7809c49b8533',
    messagingSenderId: '1010007606218',
    projectId: 'fitness-flow-dc59c',
    authDomain: 'fitness-flow-dc59c.firebaseapp.com',
    storageBucket: 'fitness-flow-dc59c.firebasestorage.app',
    measurementId: 'G-G71888JZB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_653tQKLo6klYkzMB5Tfdm3eNEk1Bo1I',
    appId: '1:1010007606218:android:832e5c299a9d02019b8533',
    messagingSenderId: '1010007606218',
    projectId: 'fitness-flow-dc59c',
    storageBucket: 'fitness-flow-dc59c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRs7yMoFKqG9OV53KkegW9g5IzKsPXn4I',
    appId: '1:1010007606218:ios:15da2a33510a37669b8533',
    messagingSenderId: '1010007606218',
    projectId: 'fitness-flow-dc59c',
    storageBucket: 'fitness-flow-dc59c.firebasestorage.app',
    iosBundleId: 'com.example.fitnessFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRs7yMoFKqG9OV53KkegW9g5IzKsPXn4I',
    appId: '1:1010007606218:ios:15da2a33510a37669b8533',
    messagingSenderId: '1010007606218',
    projectId: 'fitness-flow-dc59c',
    storageBucket: 'fitness-flow-dc59c.firebasestorage.app',
    iosBundleId: 'com.example.fitnessFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkRxRlOELSiu81nw0KF-ZZfQGynLzlHhM',
    appId: '1:1010007606218:web:80762c850c0db5099b8533',
    messagingSenderId: '1010007606218',
    projectId: 'fitness-flow-dc59c',
    authDomain: 'fitness-flow-dc59c.firebaseapp.com',
    storageBucket: 'fitness-flow-dc59c.firebasestorage.app',
    measurementId: 'G-39XNBGQZJJ',
  );
}
